parameters:
    kafka.brokers: '%env(KAFKA_BROKERS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Infrastructure\Kafka\KafkaProducer:
        arguments:
            $brokers: '%kafka.brokers%'

    App\Infrastructure\Kafka\KafkaConsumerService:
        arguments:
            $brokers: '%kafka.brokers%'
